---@class GoTestT
---@field go_test_prefix string
---@field user_command_prefix string
---@field tests_info table<string, terminal.testInfo>
---@field job_id number
---@field go_test_ns_id number
---@field term_tester termTester
---@field pin_tester PinTester
---@field displayer TestDisplay
---@field set_up fun(self: GoTestT, user_command_prefix: string)
---@field test_all fun(self: GoTestT, test_in_pkg_only: boolean)
---@field toggle_display fun(self: GoTestT)
---@field _clean_up_prev_job fun(self: GoTestT)
---@field _add_golang_test fun(self: GoTestT, entry: table, test_in_pkg_only: boolean, intermediate_path: string)
---@field _filter_golang_output fun(self: GoTestT, entry: table)
---@field _mark_outcome fun(self: GoTestT, entry: table)
---@field _setup_commands fun(self: GoTestT)
---
---@class GoTestT.Options
---@field go_test_prefix string
---@field user_command_prefix? string

---@class termTester
---@field go_test_prefix string
---@field terminal_multiplexer TerminalMultiplexer
---@field ns_id number
---@field pin_test_func fun(tests_info: terminal.testInfo)
---@field get_pinned_tests_func fun(): table<string, terminal.testInfo>
---@field get_test_info_func fun(test_name: string): terminal.testInfo
---@field add_test_info_func fun(test_info: terminal.testInfo)
---@field toggle_display_func fun(do_not_close: boolean)
---@field update_display_buffer_func fun(tests_info: table<string, terminal.testInfo>)

---@class termTest.Options
---@field go_test_prefix string
---@field ns_id number
---@field pin_test_func fun(tests_info: terminal.testInfo)
---@field get_pinned_tests_func fun(): table<string, terminal.testInfo>
---@field get_test_info_func fun(test_name: string): terminal.testInfo
---@field add_test_info_func fun(test_info: terminal.testInfo)
---@field toggle_display_func fun(do_not_close: boolean)
---@field update_display_buffer_func fun(tests_info: table<string, terminal.testInfo>)

---@class terminal.testInfo
---@field name string
---@field status string
---@field fail_at_line? number
---@field test_bufnr? number
---@field test_line? number
---@field test_command string
---@field filepath string
---@field set_ext_mark boolean
---@field output string[]

---@class PinTester
---@field go_test_prefix string
---@field pinned_list table<string, terminal.testInfo>
---@field update_display_buffer_func fun(tests_info?: table<string, terminal.testInfo>)
---@field toggle_display_func fun(boolean)
---@field retest_in_terminal_by_name fun(test_name: string)
---@field test_nearest_in_terminal_func fun(): terminal.testInfo
---@field add_test_info_func fun(test_info: terminal.testInfo)
---
---@class PinTesterOptions
---@field update_display_buffer_func fun(tests_info: table<string, terminal.testInfo>)
---@field toggle_display_func fun(boolean)
---@field retest_in_terminal_by_name fun(test_name: string)
---@field test_nearest_in_terminal_func fun(): terminal.testInfo
---@field add_test_info_func fun(test_info: terminal.testInfo)
---
---@class TestDisplay
---@field display_title string
---@field display_win_id number
---@field preview_win_id number
---@field display_bufnr number
---@field original_test_win number
---@field original_test_buf number
---@field current_buffer_lines string[]
---@field augroup_id number
---@field ns_id number
---@field _close_display fun(self: TestDisplay)
---@field toggle_term_func fun(test_name: string)
---@field rerun_in_term_func fun(test_name: string)
---@field get_tests_info_func fun(): table<string, terminal.testInfo>
---@field get_pinned_tests_func fun(): table<string, terminal.testInfo>
---@field preview_terminal_func fun(test_name: string): number? # return the win id of the floating terminal
---
---@class Test_Display_Options
---@field display_title string
---@field rerun_in_term_func fun(test_name: string)
---@field get_tests_info_func fun(): table<string, terminal.testInfo>
---@field get_pinned_tests_func fun(): table<string, terminal.testInfo>
---@field preview_terminal_func fun(test_name: string): number?    # return the win_id of the floating terminal
